<?php

namespace BusinessG\LaravelExcel\Listener;

use Psr\Container\ContainerInterface;
use BusinessG\LaravelExcel\Event\AfterExport;
use BusinessG\LaravelExcel\Event\AfterExportData;
use BusinessG\LaravelExcel\Event\AfterExportSheet;
use BusinessG\LaravelExcel\Event\AfterImport;
use BusinessG\LaravelExcel\Event\AfterImportData;
use BusinessG\LaravelExcel\Event\AfterImportSheet;
use BusinessG\LaravelExcel\Event\BeforeExport;
use BusinessG\LaravelExcel\Event\BeforeExportData;
use BusinessG\LaravelExcel\Event\BeforeExportOutput;
use BusinessG\LaravelExcel\Event\BeforeExportSheet;
use BusinessG\LaravelExcel\Event\BeforeImport;
use BusinessG\LaravelExcel\Event\BeforeImportSheet;
use BusinessG\LaravelExcel\Event\Error;
use BusinessG\LaravelExcel\Event\Event;
use BusinessG\LaravelExcel\Logger\ExcelLoggerInterface;
use BusinessG\LaravelExcel\Progress\ProgressData;
use BusinessG\LaravelExcel\Progress\ProgressInterface;

class ProgressListener extends BaseListener
{
    protected ProgressInterface $progress;

    public function __construct(ContainerInterface $container, ExcelLoggerInterface $excelLogger, ProgressInterface $progress)
    {
        parent::__construct($container, $excelLogger);

        $this->progress = $progress;
    }

    public function process(object $event): void
    {
        /**
         * @var Event $event
         */
        $enable = $this->progress->getConfig()['enable'] ?? true;
        if (!$enable || !$event->config->getIsProgress()) {
            return;
        }
        parent::process($event); // TODO: Change the autogenerated stub
    }

    function beforeExport(object $event)
    {
        /**
         * @var BeforeExport $event
         */
        $this->progress->initRecord($event->config);
    }

    function beforeExportExcel(object $event)
    {
        $this->progress->getRecord($event->config);
    }

    function beforeExportData(object $event)
    {
        /**
         * @var BeforeExportData $event
         */
        $this->progress->setSheetProgress($event->config, $event->exportCallbackParam->sheet->name, new ProgressData([
            'total' => $event->exportCallbackParam->totalCount,
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
        ]));
    }

    function beforeExportSheet(object $event)
    {
        /**
         * @var BeforeExportSheet $event
         */
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
        ]));
    }

    function beforeExportOutput(object $event)
    {
        /**
         * @var BeforeExportOutput $event
         */
        $this->progress->setProgress($event->config, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_OUTPUT,
        ]));
    }

    function afterExportData(object $event)
    {
        /**
         * @var AfterExportData $event
         */
        $success = count($event->data ?? []);
        $this->progress->setSheetProgress($event->config, $event->exportCallbackParam->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
            'success' => $success,
            'progress' => $success,
        ]));
    }

    function afterExportSheet(object $event)
    {
        /**
         * @var AfterExportSheet $event
         */
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_END,
        ]));
    }

    function afterExportExcel(object $event)
    {

        // TODO: Implement afterExportExcel() method.
    }
    function afterExportOutput(object $event)
    {
        /**
         * @var AfterExport $event
         */
        $record = $this->progress->getRecord($event->config);
        $data = $event->data ?: $record->data;
        $this->progress->setProgress($event->config, new ProgressData([
            'status' =>  ProgressData::PROGRESS_STATUS_COMPLETE ,
        ]), $data);
    }

    function afterExport(object $event)
    {
        /**
         * @var AfterExport $event
         */
        $record = $this->progress->getRecord($event->config);
        $data = $event->data ?: $record->data;
        $this->progress->setProgress($event->config, new ProgressData([
            'status' =>  ProgressData::PROGRESS_STATUS_COMPLETE ,
        ]), $data);
    }

    function beforeImport(object $event)
    {
        /**
         * @var BeforeImport $event
         */
        $this->progress->initRecord($event->config);
    }

    function beforeImportExcel(object $event)
    {
        $this->progress->getRecord($event->config);
    }

    function beforeImportSheet(object $event)
    {
        /**
         * @var BeforeImportSheet $event
         */
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
        ]));
    }

    function beforeImportData(object $event)
    {
        // TODO: Implement beforeImportData() method.
    }

    function afterImportData(object $event)
    {
        /**
         * @var AfterImportData $event
         */
        $this->progress->setSheetProgress($event->config, $event->importCallbackParam->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_PROCESS,
            'progress' => 1,
            'success' => $event->exception ? 0 : 1,
            'fail' => $event->exception ? 1 : 0,

        ]));
        if ($event->exception) {
            $this->progress->pushMessage($event->config->getToken(), $event->exception->getMessage());
        }
    }

    function afterImportExcel(object $event)
    {
        // TODO: Implement afterImportExcel() method.
    }

    function afterImportSheet(object $event)
    {
        /**
         * @var AfterImportSheet $event
         */
        $record = $this->progress->getRecord($event->config);
        $this->progress->setSheetProgress($event->config, $event->sheet->name, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_END,
            'total' => $record->sheetListProgress[$event->sheet->name]?->progress,
        ]));
    }

    function afterImport(object $event)
    {
        /**
         * @var AfterImport $event
         */
        $record = $this->progress->getRecord($event->config);
        if ($record->progress->status === ProgressData::PROGRESS_STATUS_FAIL) {
            return;
        }
        $data = $event->data ?: $record->data;
        $this->progress->setProgress($event->config, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_COMPLETE,
        ]), $data);
    }

    function beforePreCheck(object $event)
    {
    }

    function beforePreCheckData(object $event)
    {
    }

    function beforePreCheckSheet(object $event)
    {
    }

    function afterPreCheck(object $event)
    {
    }

    function afterPreCheckData(object $event)
    {
        /**
         * @var \BusinessG\LaravelExcel\Event\AfterPreCheckData $event
         */
        if (!$event->exception) {
            return;
        }
        $token = $event->config->getToken();
        if (empty($token) || !$event->config->getIsProgress()) {
            return;
        }
        $param = $event->importCallbackParam;
        $msg = sprintf('[%s] Row %d: %s',
            $param->sheet->name ?? '',
            ($param->rowIndex + 1) + ($param->sheet->headerIndex ?? 0),
            $event->exception->getMessage()
        );
        $this->progress->pushMessage($token, $msg);
    }

    function afterPreCheckSheet(object $event)
    {
    }

    function error(object $event)
    {
        /**
         * @var Error $event
         */
        $this->progress->setProgress($event->config, new ProgressData([
            'status' => ProgressData::PROGRESS_STATUS_FAIL,
            'message' => $event->exception->getMessage(),
        ]));
        $this->progress->pushMessage($event->config->getToken(), $event->exception->getMessage());
    }
}